#!/usr/bin/env python3
"""
pdf_to_py_llm.py

Extract text from a PDF and use an LLM (OpenAI) to produce Python code
implementations based on the document. The script expects the
`OPENAI_API_KEY` environment variable to be set.

Usage:
  python MyPdf/pdf_to_py_llm.py MyPdf/Pig_Documenetation.pdf -o MyPdf/generated_full.py

Dependencies:
  pip install -r MyPdf/requirements.txt

Notes:
  - The script sends the extracted text (or chunks) to the OpenAI API
    for code generation. You will be billed by OpenAI for requests.
  - Set `OPENAI_API_KEY` before running, or export it in your shell.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from typing import List, Optional

try:
    from PyPDF2 import PdfReader
except Exception:
    PdfReader = None

try:
    import openai
except Exception:
    openai = None


def extract_text_from_pdf(path: str) -> str:
    if PdfReader is None:
        raise RuntimeError("PyPDF2 is required. Install with: pip install PyPDF2")
    reader = PdfReader(path)
    parts: List[str] = []
    for page in reader.pages:
        try:
            parts.append(page.extract_text() or "")
        except Exception:
            parts.append("")
    return "\n".join(parts)


def chunk_text(text: str, max_chars: int = 4000) -> List[str]:
    # Conservative chunker that splits on paragraph boundaries
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks: List[str] = []
    current = []
    size = 0
    for p in paragraphs:
        if size + len(p) + 2 > max_chars:
            chunks.append("\n\n".join(current))
            current = [p]
            size = len(p)
        else:
            current.append(p)
            size += len(p) + 2
    if current:
        chunks.append("\n\n".join(current))
    return chunks


def call_openai_generate(prompt: str, model: str = "gpt-4") -> Optional[str]:
    if openai is None:
        raise RuntimeError("openai package is required. Install with: pip install openai")
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("Set the OPENAI_API_KEY environment variable before running")
    openai.api_key = api_key

    # Use ChatCompletion for broader compatibility
    try:
        resp = openai.ChatCompletion.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a helpful assistant that replies with Python code only when asked to generate implementations."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=3000,
        )
        content = resp["choices"][0]["message"]["content"]
        return content
    except Exception as e:
        print(f"OpenAI request failed: {e}", file=sys.stderr)
        return None


def extract_code_from_response(resp: str) -> str:
    # Extract first Python code block if present, otherwise return whole response
    m = re.search(r"```(?:python)?\n([\s\S]*?)```", resp, re.I)
    if m:
        return m.group(1).strip()
    # If no fence, try to find 'def ' occurrences and return from there
    idx = resp.find("def ")
    if idx != -1:
        return resp[idx:].strip()
    return resp.strip()


def build_prompt_from_text(text_chunk: str, instructions: str) -> str:
    prompt = (
        "The following is an excerpt from a PDF documentation.\n"
        "Read it and produce a Python implementation (or implementations) that implement the described functionality.\n"
        "Requirements:\n"
        "- Return only valid Python code (no prose).\n"
        "- Include docstrings and brief comments explaining the approach.\n"
        "- If examples are described, include small runnable examples or tests under `if __name__ == '__main__':`.\n"
        "- Keep functions small and well-named.\n\n"
    )
    prompt += "Documentation excerpt:\n\n" + text_chunk + "\n\n"
    if instructions:
        prompt += "Additional instructions:\n" + instructions + "\n\n"
    prompt += "Now generate the Python code as requested."
    return prompt


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate Python code from PDF using OpenAI LLM")
    parser.add_argument("pdf", help="Path to input PDF")
    parser.add_argument("-o", "--output", default="generated_from_pdf_llm.py", help="Output Python file")
    parser.add_argument("--model", default="gpt-4", help="OpenAI model to use (default: gpt-4)")
    parser.add_argument("--instructions", default="", help="Extra instructions for the code generator")
    args = parser.parse_args(argv)

    text = extract_text_from_pdf(args.pdf)
    chunks = chunk_text(text, max_chars=3000)

    full_code_lines: List[str] = ["# Auto-generated by pdf_to_py_llm.py"]

    for i, c in enumerate(chunks):
        print(f"Generating code for chunk {i+1}/{len(chunks)}...")
        prompt = build_prompt_from_text(c, args.instructions)
        resp = call_openai_generate(prompt, model=args.model)
        if not resp:
            print("Generation failed for chunk", i + 1, file=sys.stderr)
            continue
        code = extract_code_from_response(resp)
        full_code_lines.append("\n# --- Chunk {} ---\n".format(i + 1))
        full_code_lines.append(code)

    out = "\n".join(full_code_lines)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote generated code to {args.output}")


if __name__ == "__main__":
    main()
